// Generated by scripts/bake-idle-pose.mjs — do not edit by hand.
// Snapshot of the sailor idle arm stance (walk GLB frame 0) with a 0.13 rad
// adduction applied to each upper arm so the arms rest nearer the torso.
// Re-run `node scripts/bake-idle-pose.mjs` after changing TUCK_RAD there.

/** Local bone quaternions as [x, y, z, w], keyed by character then bone. */
export const IDLE_ARM_POSE = {
  boy: {
    LeftShoulder: [0.668613, 0.401493, -0.514838, 0.355953],
    LeftArm: [0.423636, 0.315803, 0.049392, 0.847562],
    LeftForeArm: [-0.061353, -0.083352, -0.043542, 0.993676],
    LeftHand: [0.094016, 0.076219, -0.019235, 0.992462],
    RightShoulder: [0.646802, -0.422451, 0.526678, 0.354672],
    RightArm: [0.389559, -0.282127, -0.113297, 0.869374],
    RightForeArm: [-0.073847, 0.090962, -0.049868, 0.99186],
    RightHand: [0.061512, -0.005929, -0.023559, 0.997811],
  },
  girl: {
    LeftShoulder: [0.643514, 0.384592, -0.520457, 0.408783],
    LeftArm: [0.4565, 0.363533, 0.014384, 0.811939],
    LeftForeArm: [-0.103287, -0.083734, -0.014783, 0.991011],
    LeftHand: [0.027321, 0.032432, -0.02744, 0.998724],
    RightShoulder: [0.62201, -0.399497, 0.546476, 0.393535],
    RightArm: [0.425045, -0.351544, -0.089588, 0.829293],
    RightForeArm: [-0.139094, 0.106008, -0.079564, 0.981369],
    RightHand: [0.006409, 0.032382, -0.012371, 0.999378],
  },
};

/** Adduction baked into the upper arms above, radians. */
export const IDLE_ARM_TUCK_RAD = 0.13;
